// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jopdseaukmqdbhcudduh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvcGRzZWF1a21xZGJoY3VkZHVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0Nzg0MTYsImV4cCI6MjA3MDA1NDQxNn0.07qjhtXRpQWo4kmb2lyYNhB2eUhy2nS8njMXCapu1zs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});